import { disconnectDatabase, connectDatabase } from "../src/database/index.js";
import { TimetableResultModel } from "../src/database/models/timetableResultModel.js";

const assignments = [
  // ── Monday ────────────────────────────────────────────────────────
  {
    courseCode: "AI1100",
    courseName: "Artificial Intelligence",
    courseDepartment: "Artificial Intelligence",
    professorName: "Dr. Srijith P K",
    day: "Monday",
    startTime: "09:00",
    endTime: "09:55",
    roomName: "LHC-05",
    roomCapacity: 800,
    roomDepartment: "ACADEMIC",
    students: 800,
    slotLabel: "Slot A",
    batchId: "AI24-FY",
  },
  {
    courseCode: "CS1023",
    courseName: "Software Development Fundamentals",
    courseDepartment: "Computer Science and Engineering",
    professorName: "Dr. Shirshendu Das",
    day: "Monday",
    startTime: "10:00",
    endTime: "10:55",
    roomName: "CSE-LH-02",
    roomCapacity: 70,
    roomDepartment: "CSE",
    students: 70,
    slotLabel: "Slot C",
    batchId: "CS24-FY",
  },
  {
    courseCode: "AI1013",
    courseName: "Programming for AI",
    courseDepartment: "Artificial Intelligence",
    professorName: "Dr. Karthik P N",
    day: "Monday",
    startTime: "11:00",
    endTime: "11:55",
    roomName: "LHC-08",
    roomCapacity: 120,
    roomDepartment: "ACADEMIC",
    students: 120,
    slotLabel: "Slot C",
    batchId: "AI24-FY",
  },
  {
    courseCode: "CE1100",
    courseName: "Construction Materials",
    courseDepartment: "Civil Engineering",
    professorName: "Dr. Meenakshi Sharma",
    day: "Monday",
    startTime: "12:00",
    endTime: "12:55",
    roomName: "A-Class Room 118",
    roomCapacity: 84,
    roomDepartment: "ACADEMIC",
    students: 84,
    slotLabel: "Slot D",
    batchId: "CE24-FY",
  },
  // ── Tuesday ───────────────────────────────────────────────────────
  {
    courseCode: "AI2100",
    courseName: "Deep Learning",
    courseDepartment: "Artificial Intelligence",
    professorName: "Dr. Srijith P K",
    day: "Tuesday",
    startTime: "14:30",
    endTime: "15:55",
    roomName: "LHC-13",
    roomCapacity: 320,
    roomDepartment: "ACADEMIC",
    students: 320,
    slotLabel: "Slot R",
    batchId: "AI24-FY",
  },
  {
    courseCode: "BT2063",
    courseName: "Molecular and Cellular Biology",
    courseDepartment: "Biotechnology",
    professorName: "Dr. Gunjan Mehta",
    day: "Tuesday",
    startTime: "16:00",
    endTime: "17:25",
    roomName: "LHC-05",
    roomCapacity: 800,
    roomDepartment: "ACADEMIC",
    students: 800,
    slotLabel: "Slot S",
    batchId: "BT24-FY",
  },
  // ── Wednesday ─────────────────────────────────────────────────────
  {
    courseCode: "CH2190",
    courseName: "Fluid Mechanics",
    courseDepartment: "Chemical Engineering",
    professorName: "Dr. Ranajit Mondal",
    day: "Wednesday",
    startTime: "09:00",
    endTime: "09:55",
    roomName: "A-Class Room 118",
    roomCapacity: 84,
    roomDepartment: "ACADEMIC",
    students: 84,
    slotLabel: "Slot B",
    batchId: "CH24-FY",
  },
  {
    courseCode: "CS3563",
    courseName: "Introduction to DBMS II",
    courseDepartment: "Computer Science and Engineering",
    professorName: "Dr. Anupam Sanghi",
    day: "Wednesday",
    startTime: "11:00",
    endTime: "11:55",
    roomName: "LHC-08",
    roomCapacity: 120,
    roomDepartment: "ACADEMIC",
    students: 120,
    slotLabel: "Slot F",
    batchId: "CS22-TY",
  },
  {
    courseCode: "AI1110",
    courseName: "Probability and Random Variables",
    courseDepartment: "Artificial Intelligence",
    professorName: "Dr. Vajha Myna",
    day: "Wednesday",
    startTime: "14:30",
    endTime: "15:55",
    roomName: "LHC-14",
    roomCapacity: 200,
    roomDepartment: "ACADEMIC",
    students: 200,
    slotLabel: "Slot F",
    batchId: "AI24-FY",
  },
  // ── Thursday ──────────────────────────────────────────────────────
  {
    courseCode: "EE1010",
    courseName: "Electrical Circuits",
    courseDepartment: "Electrical Engineering",
    professorName: "Dr. Arun Kumar",
    day: "Thursday",
    startTime: "09:00",
    endTime: "09:55",
    roomName: "LHC-07",
    roomCapacity: 200,
    roomDepartment: "ACADEMIC",
    students: 150,
    slotLabel: "Slot C",
    batchId: "EE24-FY",
  },
  {
    courseCode: "ME1010",
    courseName: "Engineering Mechanics",
    courseDepartment: "Mechanical Engineering",
    professorName: "Prof. Mechanical",
    day: "Thursday",
    startTime: "10:00",
    endTime: "10:55",
    roomName: "A-Class Room 119",
    roomCapacity: 108,
    roomDepartment: "ACADEMIC",
    students: 100,
    slotLabel: "Slot A",
    batchId: "ME24-FY",
  },
  {
    courseCode: "AI3703",
    courseName: "Natural Language Processing",
    courseDepartment: "Artificial Intelligence",
    professorName: "Dr. Maunendra Sankar Desarkar",
    day: "Thursday",
    startTime: "14:30",
    endTime: "15:55",
    roomName: "LHC-08",
    roomCapacity: 120,
    roomDepartment: "ACADEMIC",
    students: 120,
    slotLabel: "Slot Q",
    batchId: "AI22-TY",
  },
  // ── Friday ────────────────────────────────────────────────────────
  {
    courseCode: "CH2180",
    courseName: "Heat Transfer",
    courseDepartment: "Chemical Engineering",
    professorName: "Dr. Suhanya Duraiswamy",
    day: "Friday",
    startTime: "09:00",
    endTime: "09:55",
    roomName: "A-Class Room 118",
    roomCapacity: 84,
    roomDepartment: "ACADEMIC",
    students: 84,
    slotLabel: "Slot E",
    batchId: "CH24-FY",
  },
  {
    courseCode: "CS2030",
    courseName: "Theory of Computation",
    courseDepartment: "Computer Science and Engineering",
    professorName: "Dr. Nitin Saurabh",
    day: "Friday",
    startTime: "10:00",
    endTime: "10:55",
    roomName: "A-LH-2",
    roomCapacity: 184,
    roomDepartment: "ACADEMIC",
    students: 184,
    slotLabel: "Slot F",
    batchId: "CS24-FY",
  },
  {
    courseCode: "BM1030",
    courseName: "Bioengineering",
    courseDepartment: "BioMedical Engineering",
    professorName: "Dr. Nagarajan Ganapathy",
    day: "Friday",
    startTime: "14:30",
    endTime: "15:55",
    roomName: "LHC-12",
    roomCapacity: 200,
    roomDepartment: "ACADEMIC",
    students: 200,
    slotLabel: "Slot S",
    batchId: "BM24-FY",
  },
  {
    courseCode: "AI3013",
    courseName: "AI for Humanity",
    courseDepartment: "Artificial Intelligence",
    professorName: "Dr. Arun Kumar",
    day: "Friday",
    startTime: "16:00",
    endTime: "17:25",
    roomName: "LHC-11",
    roomCapacity: 120,
    roomDepartment: "ACADEMIC",
    students: 120,
    slotLabel: "Slot R",
    batchId: "CS22-TY",
  },
];

const run = async () => {
  await connectDatabase();

  console.log("Wiping existing published timetables to avoid version conflicts...");
  await TimetableResultModel.updateMany({ isLatest: true }, { isLatest: false });

  console.log("Seeding a 'nice' Timetable schedule for Bulk Rescheduling tests...");
  const newVersion = `published-${Date.now()}`;

  await TimetableResultModel.create({
    version: newVersion,
    status: "published",
    isLatest: true,
    academicYear: "2025-2026",
    semester: 2,
    assignments: assignments,
    generatedAt: new Date(),
    stats: {
      totalAssignments: assignments.length,
      timeslotCount: 20,
      unassignedCourseCount: 0,
      unassignedCourses: [],
      solverDuration: 42.5,
      solverStatus: "OPTIMAL",
    },
    constraints: {},
  });

  console.log(`Successfully seeded published timetable version: ${newVersion}`);
  console.log(`It contains ${assignments.length} assignments spanning Mon-Fri.`);
  console.log("You can now test Bulk Rescheduling workflows!");
};

run()
  .then(async () => {
    await disconnectDatabase();
    process.exit(0);
  })
  .catch(async (error) => {
    console.error("Nice Timetable seed failed:", error.message);
    await disconnectDatabase();
    process.exit(1);
  });
